language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - yarn global add typescript
  - yarn
service: 
  - postgresql
before_script:
  - psql -c 'create database resman-admin-api;' -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD password;" -U postgres
  - yarn typeorm migration:run